name: Action_Kernel


on:

  push:
    branches: [ Clang ]
  pull_request:
    branches: [ Clang ]




jobs:

  build:

    runs-on: ubuntu-18.04


    steps:

      - uses: actions/checkout@v2

      - name: Load Configuration
        uses: falti/dotenv-action@v0.2.5
        id: config
        with:
          path: config.env

      - name: Check Configuration
        run: |
          function required () { if ! [[ "$1" ]]; then echo "$2 variable can't be null." && exit 1; fi }
          required "${{ steps.config.outputs.kernel_name }}" "KERNEL_NAME config"
          required "${{ steps.config.outputs.branch_name }}" "BRANCH_NAME config"
          required "${{ steps.config.outputs.kernel_url }}" "KERNEL_URL config"
 
      - name: Git kernel
        run: |
          git clone --depth 1 "${{ steps.config.outputs.kernel_url }}" -b "${{ steps.config.outputs.branch_name }}" kernel


















      - name: Setup Environment
        run: |
          git clone --depth=1 https://github.com/kdrag0n/proton-clang $CLANG_PATH
          sh -c "$(curl -sSL https://github.com/akhilnarang/scripts/raw/master/setup/android_build_env.sh/)"

      - name: Make kernel
        run: |
          sudo mv build.sh $GITHUB_WORKSPACE/kernel
          cd $GITHUB_WORKSPACE/kernel
          bash ./build.sh

      - name: Upload to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "$GITHUB_WORKSPACE/kernel/out/arch/arm64/boot/Image.gz-dtb,$GITHUB_WORKSPACE/kernel/out/arch/arm64/boot/dtbo.img"
          
          tag: "${{ steps.config.outputs.kernel_name }}"
          token: ${{ secrets.GITHUB_TOKEN }}
