name: Action_Kernel


on:

  push:
    branches: [ alioth ]
  pull_request:
    branches: [ alioth ]




jobs:

  build:

    runs-on: ubuntu-22.04


    steps:

      - uses: actions/checkout@v2

      - name: Load Configuration
        uses: falti/dotenv-action@v0.2.5
        id: config
        with:
          path: config.env

      - name: Check Configuration
        run: |
          function required () { if ! [[ "$1" ]]; then echo "$2 variable can't be null." && exit 1; fi }
          required "${{ steps.config.outputs.kernel_name }}" "KERNEL_NAME config"
          required "${{ steps.config.outputs.branch_name }}" "BRANCH_NAME config"
          required "${{ steps.config.outputs.kernel_url }}" "KERNEL_URL config"
 
      - name: Apt install
        run: |
          sudo apt install -y bc bison build-essential curl flex g++-multilib gcc-multilib python3

          sudo apt install -y git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev

          sudo apt install -y lib32z1-dev liblz4-tool clang libncurses5 libncurses5-dev libsdl1.2-dev

          sudo apt install -y libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lzop pngcrush

          sudo apt install -y schedtool squashfs-tools xsltproc zip zlib1g-dev unzip python2 python-is-python3


 
      - name: Git kernel source
        run: |
          git clone --depth 1 "${{ steps.config.outputs.kernel_url }}" -b "${{ steps.config.outputs.branch_name }}" kernel

      - name: Setup environment
        run: |

          echo "pass"


      - name: Build kernel
        run: |
          sudo mv build.sh $GITHUB_WORKSPACE/kernel
          cd $GITHUB_WORKSPACE/kernel
          bash ./build.sh

      - name: Upload to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "kernel/out/arch/arm64/boot/Image.gz-dtb,kernel/out/arch/arm64/boot/dtbo.img"
          tag: "${{ steps.config.outputs.kernel_name }}"
          token: ${{ secrets.GITHUB_TOKEN }}
